include:
  - project: gitlab/include
    ref: master
    file:
      - ci/template-build-image.yml
      - ci/scanner.yml
      - helmfile.yml

stages:
  - build-artifacts
  - build
  - scan
  - deploy

variables:
  K8S_HOST: ${CI_PROJECT_NAME}-suz.${K8S_DOMAIN}
  SEMGREP_ID: ce315152-438a-421e-b3ae-7411bd545fe0
  TRIVY_IMAGE_ID: fe3d5ef3-5197-4225-afbe-36a057cdd83b

build-artifacts:
  stage: build-artifacts
  image: docker-base.loodsen.ru/gradle:8.9-jdk21
  script:
    - gradle build --no-daemon
  artifacts:
    paths:
      - build/libs/SYZ_Gateway-0.0.1-SNAPSHOT.jar
    expire_in: 1 hour
  tags:
    - docker1

build-dev:
  stage: build
  extends: .build-image
  needs:
    - build-artifacts
  variables:
    DOCKER_TAG: ${CI_COMMIT_REF_SLUG}
  before_script:
    - export JAVA_APP=$(find java_out -iname *.jar | head -n 1)
    - export DOCKER_PARAMETERS="--build-arg=ARG_JAVA_APP=${JAVA_APP}"
  rules:
    - if: $CI_COMMIT_REF_NAME !~ /^(master|develop)$/
      when: never
    - when: on_success
  tags:
    - docker1

semgrep:
  extends: .run-scanner
  script:
    - !reference [.scan-code-semgrep]
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"

trivy-image:
  extends: .run-scanner
  script:
    - !reference [.docker-scan]
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"

deploy:
  stage: deploy
  image: ${ANSIBLE_IMAGE}
  needs:
    - build-dev
  variables:
    K8S_NAMESPACE: suz
    K8S_PROJECT_NAME: ${CI_PROJECT_NAME}
    K8S_PROJECT_IMAGE: ${REGISTRY_HOST}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
    K8S_DOMAIN: k8s.ldsn.dev
    HELMFILE: helmfile.yml
    HELMFILE_DIR: .helmfile
    JAVA_TOOL_OPTIONS: -Dspring.profiles.active=${ACTIVE_PROFILES}
    ISSUER_URI: "http://keycloak/realms/RandomUsers"
    JWK_SET_URI: "http://keycloak/realms/RandomUsers/protocol/openid-connect/certs"
    ALLOWED_ORIGINS: "http://localhost:5173,http://localhost:8080,https://main.k8s.ldsn.dev"
    KEYCLOAK_URL: "http://keycloak"
    PERMIT_ALL_URIS: "/actuator/**,/metrics/**,/realms/RandomUsers/**,/auth/**,/resources/**,/swagger/**,/api-docs/**,/api/v1/keycloak/**"
  script:
    - !reference [ .helmfile ]
  rules:
    - if: $CI_COMMIT_REF_NAME !~ /^(master|develop)$/
      when: never
    - when: manual
  tags:
    - k8s-99
