spring:

  security:
    excluded:
      urls: ${EXCLUDED_URLS:/actuator,/metrics}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER-URI:http://localhost:8081/realms/RandomUsers}
          jwk-set-uri: ${JWK-SET-URI:http://localhost:8081/realms/RandomUsers/protocol/openid-connect/certs}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:SpringGatewayService}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:g1CLYkdeg3oyUkbR9BD3HjSydgMwVnkH}
            scope: ${KEYCLOAK_SCOPE:openid}
            authorization-grant-type: ${KEYCLOAK_AUTHORIZATION_GRANT_TYPE:authorization_code}
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}
            client-name: ${KEYCLOAK_CLIENT_NAME:Keycloak}
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_AUTH_URI:http://localhost:8081/realms/RandomUsers/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8081/realms/RandomUsers/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:http://localhost:8081/realms/RandomUsers/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8081/realms/RandomUsers/protocol/openid-connect/certs}
            user-name-attribute: ${KEYCLOAK_USER_NAME_ATTRIBUTE:preferred_username}
  cloud:
    gateway:
      default-filters: [ ]
      routes:
#        - id: actuator-endpoints
#          uri: http://ya.ru
#          predicates:
#            - Path=/actuator/**
#          filters: [ ]
#
#        - id: metrics-endpoints
#          uri: http://localhost:8080/
#          predicates:
#            - Path=/metrics/**
#          filters: [ ]



management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8080

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    filters: DEBUG
  pattern:
    console: "%c %d{yyyy-MM-dd HH:mm:ss} - %msg%n"

